num1 <- as.numeric(readline(prompt = "Primer número: "))
num2 <- as.numeric(readline(prompt = "Segon número: "))
cat("Suma:", num1 + num2, "\n")
cat("Resta:", num1 - num2, "\n")
cat("Producte:", num1 * num2, "\n")
cat("Divisió:", num1 / num2, "\n")
