num1 <- as.numeric(readline(prompt = "Nota pràctica: "))
num2 <- as.numeric(readline(prompt = "Nota teòrica: "))
num3 <- as.numeric(readline(prompt = "Nota participacio: "))
nota_final <- (num1*0.3) + (num2*0.6) + (num3*0.10)
cat("Nota final:", nota_final, "\n")